import { Ratio, Metric } from "@src/models/FinancialMetrics.interface";


export const ratios: Ratio[] = [
  {
    key: "TrailingPE",
    name: "Trailing Price to Earning Ratio",
    formula: "Net Income / Shareholder's Equity",
    description: "A measure of a company's profitability that "+
      "reveals how much profit a company generates "+
      "with the money shareholders have invested.",
    historicalData: [
      { date: "", value: "" },
    ],
  },

  {
    key: "ForwardPE",
    name: "Forward Price to Earning Ratio",
    formula: "Market Value per Share / Forecasted Earnings per Share",
    description: "A measure of the price-to-earnings "+
    "ratio using forecasted earnings for the P/E calculation.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "PriceToSalesRatioTTM",
    name: "Price to Sales Ratio (TTM)",
    formula: "Price per Share / Revenue per Share",
    description: "A valuation ratio that compares" +
    "a company's stock price to its revenues.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "PriceToBookRatio",
    name: "Price to Book Ratio",
    formula: "Market Value per Share / Book Value per Share",
    description: "A ratio used to compare "+
    "a stock's market value to its book value.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "EVToRevenue",
    name: "Enterprise Value to Revenue",
    formula: "Enterprise Value / Revenue",
    description: "A measure of the value of"+
    "a company that compares enterprise value to revenue.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "EVToEBITDA",
    name: "Enterprise Value to EBITDA",
    formula: "Enterprise Value / EBITDA",
    description: "A measure of the value of a company "+
    "that compares enterprise value to EBITDA.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "PEGRatio",
    name: "PEG Ratio",
    formula: "P/E Ratio / Annual EPS Growth",
    description: "A valuation metric for determining the relative trade-off "+
    "between the price of a stock, the earnings generated per share (EPS), "+
    "and the company's expected growth.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "Beta",
    name: "Beta",
    formula: "Covariance(ROA, ROM) / Variance(ROM)",
    description: "A measure of the volatility, or systematic risk, "+
    "of a security or portfolio compared to the market as a whole.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "ProfitMargin",
    name: "Profit Margin",
    formula: "Net Income / Revenue",
    description: "A measure of profitability that calculates "+
    "the percentage of revenue that exceeds costs.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "OperatingMarginTTM",
    name: "Operating Margin (TTM)",
    formula: "Operating Income / Revenue",
    description: "A profitability ratio calculated as "+
    "operating income divided by revenue.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "ReturnOnAssetsTTM",
    name: "Return on Assets (TTM)",
    formula: "Net Income / Total Assets",
    description: "An indicator of how profitable a "+
    "company is relative to its total assets.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "ReturnOnEquityTTM",
    name: "Return on Equity (TTM)",
    formula: "Net Income / Shareholder's Equity",
    description: "A measure of financial performance calculated "+
    "by dividing net income by shareholder's equity.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  { 
    key: "RevenueTTM",
    name: "Revenue (TTM)",
    formula: "Total Sales Revenue over the Trailing Twelve Months",
    description: "Total revenue generated by a "+
    "company over the trailing twelve months.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "GrossProfitTTM",
    name: "Gross Profit (TTM)",
    formula: "Total Revenue - Cost of Goods Sold",
    description: "Gross profit generated by a" +
    "company over the trailing twelve months.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
// Add more ratios as needed
];

export const incomeStatementMetrics: Metric[] = [
  {
    key: "grossProfit",
    name: "Gross Profit",
    formula: "Total Revenue - Cost of Revenue",
    description: "Gross profit is the profit a company makes after "+
    "deducting the costs associated with making and selling its products.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "totalRevenue",
    name: "Total Revenue",
    formula: "Total Revenue from all sources",
    description: "Total revenue is the sum of all revenue "+
    "streams a company earns from its operations.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "costOfRevenue",
    name: "Cost of Revenue",
    formula: "Total Cost of Goods Sold",
    description: "Cost of revenue is the total cost of manufacturing "+
    "and delivering a product or service to consumers.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "operatingIncome",
    name: "Operating Income",
    formula: "Gross Profit - Operating Expenses",
    description: "Operating income is the profit realized "+
    "from a business's operations.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "sellingGeneralAndAdministrative",
    name: "Selling, General and Administrative Expenses",
    formula: "Total Selling, General and Administrative Expenses",
    description: "SG&A expenses include all non-production "+
    "related expenses incurred by a company.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "researchAndDevelopment",
    name: "Research and Development Expenses",
    formula: "Total Research and Development Expenses",
    description: "R&D expenses are the costs a company incurs "+
    "for researching and developing new products.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "netIncome",
    name: "Net Income",
    formula: "Total Revenue - Total Expenses",
    description: "Net income is the total profit of a company after "+
    "all expenses and taxes have been deducted.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  // Add more income statement metrics as needed
];

export const cashFlowMetrics: Metric[] = [
  {
    key: "operatingCashflow",
    name: "Operating Cash Flow",
    formula: "Cash Inflows - Cash Outflows from Operating Activities",
    description: "Operating cash flow is the cash generated "+
    "from the normal operations of a business.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "capitalExpenditures",
    name: "Capital Expenditures",
    formula: "Total Capital Expenditures",
    description: "Capital expenditures are funds used by a company to acquire,"+
    "upgrade, and maintain physical assets such as property, "+
    "industrial buildings, or equipment.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "cashflowFromInvestment",
    name: "Cash Flow from Investment",
    formula: "Total Cash Flow from Investing Activities",
    description: "Cash flow from investing activities includes the purchase "+
    "and sale of long-term investments and property, plant, and equipment.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "cashflowFromFinancing",
    name: "Cash Flow from Financing",
    formula: "Total Cash Flow from Financing Activities",
    description: "Cash flow from financing activities includes the inflow "+
    "of cash from investors such as banks or shareholders, "+
    "as well as the outflow of cash to shareholders as dividends.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "dividendPayout",
    name: "Dividend Payout",
    formula: "Total Dividend Payout",
    description: "Dividend payout is the sum of all "+
    "dividends paid to shareholders.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  // Add more cash flow metrics as needed
];

export const balanceSheetMetrics: Metric[] = [
  {
    key: "totalAssets",
    name: "Total Assets",
    formula: "Liabilities + Shareholder's Equity",
    description: "Total assets represent everything "+
    "of value that is owned by a company.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "totalCurrentAssets",
    name: "Total Current Assets",
    formula: "Sum of all current assets",
    description: "Total current assets include cash, accounts receivable, "+
    "inventory, and other assets that are expected to be "+
    "converted to cash within a year.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "cashAndCashEquivalentsAtCarryingValue",
    name: "Cash and Cash Equivalents",
    formula: "Sum of all cash and cash equivalents",
    description: "Cash and cash equivalents include currency, "+
    "bank accounts, and other liquid financial instruments.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "inventory",
    name: "Inventory",
    formula: "Total Inventory",
    description: "Inventory includes raw materials, work-in-progress, "+
    "and finished goods held by a company.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "currentNetReceivables",
    name: "Net Receivables",
    formula: "Total Receivables - Allowances for Doubtful Accounts",
    description: "Net receivables represent the amount of money a company "+
      "expects to receive from its customers after "+
      "accounting for doubtful accounts.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "totalLiabilities",
    name: "Total Liabilities",
    formula: "Sum of all liabilities",
    description: "Total liabilities include both current "+
    "and long-term obligations.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "totalCurrentLiabilities",
    name: "Total Current Liabilities",
    formula: "Sum of all current liabilities",
    description: "Total current liabilities include short-term "+
    "obligations that are due within a year.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "shortTermDebt",
    name: "Short Term Debt",
    formula: "Total Short Term Debt",
    description: "Short term debt includes all "+
    "debt obligations due within one year.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "longTermDebt",
    name: "Long Term Debt",
    formula: "Total Long Term Debt",
    description: "Long term debt includes all debt "+
    "obligations due after one year.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  {
    key: "totalShareholderEquity",
    name: "Total Shareholder Equity",
    formula: "Total Assets - Total Liabilities",
    description: "Total shareholder equity is the net value "+
    "of a company, calculated as total assets minus total liabilities.",
    historicalData: [
      { date: "", value: "" },
    ],
  },
  // Add more balance sheet metrics as needed
];